#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '💪  Running application to test that everything is fine...'

# Check testing
yarn test:e2e ||
(
    echo '🤡😂❌🤡 Test check failed. 🤡😂❌🤡
            Are you seriously trying to write that? Make the changes required above.'
    false;
)

echo '🤔🤔🤔🤔... Alright... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'

yarn build ||
(
    echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
            Next build failed: View the errors above to see why. 
    '
    false;
)

# Show coverage details
npx nyc report --reporter=lcov --reporter=text

# If everything passes... Now we can push
echo '✅✅✅✅ You win this time... I am pushing this now. ✅✅✅✅'
